version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - CLICKHOUSE_URI=https://root:password@clickhouse:8123
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=growthbook
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=password
volumes:
  uploads:
  mongodata:
