app = 'growthbook'
org = 'growthbook'
primary_region = 'sjc'

[build]

[[services]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = "80"

[[services]]
  internal_port = 3100
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = "8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
