name: CI
on:
  pull_request:
    paths-ignore:
      - "packages/**"
      - "yarn.lock"
      - ".eslintrc"
      - ".eslintignore"
      - ".prettierignore"

# If nothing of importance changed, the normal CI workflow is skipped
# Skipped steps do not count as successful, which will block the PR from being merged
# This is a dummy workflow for those cases so it gets marked as successful in GitHub
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Test Upload to S3
          run: |
            # Echo Something
            echo "Is this thing working?"
      - run: 'echo "No changes, skipping"'