name: CI
on:
  pull_request:
    paths-ignore:
      - "packages/**"
      - "yarn.lock"
      - ".eslintrc"
      - ".eslintignore"
      - ".prettierignore"
  # If nothing of importance changed, the normal CI workflow is skipped
  # Skipped steps do not count as successful, which will block the PR from being merged
  # This is a dummy workflow for those cases so it gets marked as successful in GitHub
  # jobs:
  #   ci:
  #     runs-on: ubuntu-latest
  #     steps:
  #       run: |
  #         echo 1. Starting CI process bro...
  #         echo 2. What environment variables are available?
  #         env
  # jobs:
  #   ci:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Show env variables
  #         run: |
  #           echo 1. Starting CI process bro...
  #           echo 2. What environment variables are available?
  #           echo 3. ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           ${{ secrets.AWS_ACCESS_KEY_ID }}

  jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Download static files
          run: |
            echo Starting download process
            echo Downloading growthbook/growthbook:latest
            docker pull growthbook/growthbook:latest
        # - name: Upload Chunks to S3
        # uses: jakejarvis/s3-sync-action@master
        # with:
        #   args: --acl public-read --delete
        # env:
        #   AWS_S3_BUCKET: my-s3-bucket-name
        #   AWS_REGION: us-east-1
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   SOURCE_DIR: ./front-end/.next/static/chunks

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Show env variables
#         run: |
#           echo 1. Download the docker image
#           docker pull growthbook/growthbook:latest
#           echo 2. What environment variables are available?
#           echo 3. ${{ secrets.AWS_ACCESS_KEY_ID }}
#           ${{ secrets.AWS_ACCESS_KEY_ID }}

# - run: echo env
# - run: 'echo "No changes, skipping - is this thing on?"'
# - run:
#   # Download the docker image
#   'docker pull growthbook/growthbook:latest'
#   # Pull out static assets
#   'docker run -it growthbook/growthbook:latest bash'
#   # (I don't think I need this anymore) cd packages/front-end/.next/static/chunks
#   # Download all of the files in the current directory
#   'wget -r -l1 --no-parent /front-end/.next/static/chunks'
#   # Echo env variables
#   'echo env'
