name: CI
on:
  pull_request:
    paths-ignore:
      - "packages/**"
      - "yarn.lock"
      - ".eslintrc"
      - ".eslintignore"
      - ".prettierignore"

# If nothing of importance changed, the normal CI workflow is skipped
# Skipped steps do not count as successful, which will block the PR from being merged
# This is a dummy workflow for those cases so it gets marked as successful in GitHub
jobs:
  ci:
    runs-on: ubuntu-latest
    # needs: [docker]
    steps:
      # - run: 'echo "No changes, skipping"'
      - name: Copy static files from Docker Container
        run: docker pull growthbook/growthbook
      # - name: Copy static files from Docker Container
      #   run: docker pull growthbook/growthbook
      # - name: Start the container with the name 'gb'
      #   run: docker run --name gb growthbook/growthbook
      # - name: Get the container id
      #   run: docker ps -aqf "name=gb"
      #   register: CONTAINER_ID
      # - name: Echo CONTAINER_ID
      #   run: echo ${{ CONTAINER_ID }}
      # - name: Create a tmp folder
      #   run: mkdir tmp && cd tmp && pwd
      #   register: TEMP_PATH
      # - name: Echo TEMP_PATH
      #   run: echo ${{ TEMP_PATH }}
