name: CI
on:
  pull_request:
    paths-ignore:
      - "packages/**"
      - "yarn.lock"
      - ".eslintrc"
      - ".eslintignore"
      - ".prettierignore"
  # If nothing of importance changed, the normal CI workflow is skipped
  # Skipped steps do not count as successful, which will block the PR from being merged
  # This is a dummy workflow for those cases so it gets marked as successful in GitHub
  # jobs:
  #   ci:
  #     runs-on: ubuntu-latest
  #     steps:
  #       run: |
  #         echo 1. Starting CI process bro...
  #         echo 2. What environment variables are available?
  #         env
  jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Show env variables
          run: |
            echo 1. Starting CI process bro...
            echo 2. What environment variables are available?
            env
