name: PR Preview Environment

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - "!**.md"
      - "yarn.lock"
      - "Dockerfile"
      - ".dockerignore"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  preview:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
      cancel-in-progress: true
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Deploy MongoDB
      #   uses: superfly/fly-pr-review-apps@1.3.0
      #   env:
      #     MONGO_INITDB_ROOT_USERNAME: root
      #     MONGO_INITDB_ROOT_PASSWORD: password
      #   with:
      #     org: growthbook
      #     region: sjc
      #     image: "mongo:latest"
      #     name: pr-${{ github.event.number }}-growthbook-mongo

      - name: Deploy PR to fly
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MONGODB_URI: mongodb://root:password@pr-${{ github.event.number }}-growthbook-mongo.internal/growthbook?authSource=admin
          APP_ORIGIN: https://pr-${{ github.event.number }}-growthbook.fly.dev
          API_HOST: https://pr-${{ github.event.number }}-growthbook.fly.dev:8080
        with:
          org: growthbook
          region: sjc
