name: PR Preview Environment

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - "!**.md"
      - "yarn.lock"
      - "Dockerfile"
      - ".dockerignore"
    types: [opened, synchronize, reopened, ready_for_review]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: sjc
  FLY_ORG: growthbook

jobs:
  preview:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
      cancel-in-progress: true
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy PR to fly
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
